sonar.projectKey=darts-tournament
sonar.projectName=Darts Tournament
sonar.projectVersion=1.0

sonar.sources=backend/src,frontend/src,shared/src
sonar.tests=backend/tests,frontend/tests

sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/logs/**,**/uploads/**,**/*.d.ts,frontend/srv/locales/**,frontend/src/locales/**

sonar.typescript.tsconfigPath=backend/tsconfig.json,frontend/tsconfig.sonar.json
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
