FROM node:20-bookworm-slim

RUN apt-get update -y && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /app/backend

COPY package*.json ./
COPY prisma ./prisma
RUN npm ci

COPY src ./src
COPY scripts ./scripts
COPY tsconfig.json ./tsconfig.json
COPY eslint.config.cjs ./eslint.config.cjs
COPY jest.config.js ./jest.config.js

EXPOSE 3000

CMD ["npm", "run", "dev"]
